ci:
  config:
    schema_version: 1
    trunk_branch: main
    triggers:
      - src/**
    environments:
      - test
      - staging
      - prod
    cli_version: v0.5.0-rc.10
    state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
    manifest_file: .github/manifest.yaml
    manifest_key: ci
    validate:
      workflow: .github/workflows/validate.yaml
      triggers:
        - src/**
      on_failure: abort
      retries: 1
    builds:
      - name: base
        workflow: .github/workflows/build-base.yaml
        triggers: []
        retries: 2
        secrets: inherit
        permissions:
          contents: read
          id-token: write
      - name: app
        workflow: .github/workflows/build-app.yaml
        triggers: []
        depends_on:
          - base
        auto_commits: true
    deploys:
      - name: app
        workflow: .github/workflows/deploy-app.yaml
        triggers: []
  state:
    prod:
      sha: 267d32bcc5185ea9437b217f0ed4dbec379f9f6b
      version: v0.1.0
      committed_at: "2026-06-26T06:45:15Z"
      committed_by: joshua-temple
      deploys:
        app:
          sha: 267d32bcc5185ea9437b217f0ed4dbec379f9f6b
          version: v0.1.0
          deployed_at: "2026-06-26T06:45:15Z"
          deployed_by: joshua-temple
    release:
      sha: 267d32bcc5185ea9437b217f0ed4dbec379f9f6b
      version: v0.1.0
      committed_at: "2026-06-26T06:45:15Z"
      committed_by: joshua-temple
    staging:
      sha: 267d32bcc5185ea9437b217f0ed4dbec379f9f6b
      version: v0.1.0-rc.0
      committed_at: "2026-06-26T06:44:11Z"
      committed_by: joshua-temple
      deploys:
        app:
          sha: 267d32bcc5185ea9437b217f0ed4dbec379f9f6b
          version: v0.1.0-rc.0
          deployed_at: "2026-06-26T06:44:11Z"
          deployed_by: joshua-temple
    test:
      sha: 3f7099d7a5240a41c66ee93513e0352e454568b2
      version: v0.2.0-rc.0
      committed_at: "2026-06-26T06:46:21Z"
      committed_by: joshua-temple
      builds:
        app:
          sha: 267d32bcc5185ea9437b217f0ed4dbec379f9f6b
          artifact_id: app-267d32bcc5185ea9437b217f0ed4dbec379f9f6b
        base:
          sha: 267d32bcc5185ea9437b217f0ed4dbec379f9f6b
          artifact_id: base-267d32bcc5185ea9437b217f0ed4dbec379f9f6b
      deploys:
        app:
          sha: 267d32bcc5185ea9437b217f0ed4dbec379f9f6b
          deployed_at: "2026-06-26T06:43:20Z"
          deployed_by: joshua-temple
  latest_release:
    version: v0.1.0
    sha: 267d32bcc5185ea9437b217f0ed4dbec379f9f6b
    released_on: "2026-06-26T06:45:15Z"
    released_by: joshua-temple
