ci:
  config:
    schema_version: 1
    trunk_branch: main
    triggers:
      - src/**
    environments:
      - test
      - staging
      - prod
    cli_version: v0.6.0-rc.2
    state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
    manifest_file: .github/manifest.yaml
    manifest_key: ci
    validate:
      workflow: .github/workflows/validate.yaml
      triggers:
        - src/**
      on_failure: abort
      retries: 1
    builds:
      - name: base
        workflow: .github/workflows/build-base.yaml
        triggers: []
        retries: 2
        secrets: inherit
        permissions:
          contents: read
          id-token: write
      - name: app
        workflow: .github/workflows/build-app.yaml
        triggers: []
        depends_on:
          - base
        auto_commits: true
    deploys:
      - name: app
        workflow: .github/workflows/deploy-app.yaml
        triggers: []
  state:
    prod:
      sha: cd58c87978165b20d981e344fac0b3509879456f
      version: v0.1.0
      committed_at: "2026-06-30T08:18:58Z"
      committed_by: joshua-temple
      deploys:
        app:
          sha: cd58c87978165b20d981e344fac0b3509879456f
          version: v0.1.0
          deployed_at: "2026-06-30T08:18:58Z"
          deployed_by: joshua-temple
    release:
      sha: cd58c87978165b20d981e344fac0b3509879456f
      version: v0.1.0
      committed_at: "2026-06-30T08:18:58Z"
      committed_by: joshua-temple
    staging:
      sha: cd58c87978165b20d981e344fac0b3509879456f
      version: v0.1.0-rc.0
      committed_at: "2026-06-30T08:17:51Z"
      committed_by: joshua-temple
      deploys:
        app:
          sha: cd58c87978165b20d981e344fac0b3509879456f
          version: v0.1.0-rc.0
          deployed_at: "2026-06-30T08:17:51Z"
          deployed_by: joshua-temple
    test:
      sha: 8d7c3f692b55940c5b1637c93d0a31437ab48c76
      version: v0.2.0-rc.0
      committed_at: "2026-06-30T08:20:18Z"
      committed_by: joshua-temple
      builds:
        app:
          sha: cd58c87978165b20d981e344fac0b3509879456f
          artifact_id: app-cd58c87978165b20d981e344fac0b3509879456f
        base:
          sha: cd58c87978165b20d981e344fac0b3509879456f
          artifact_id: base-cd58c87978165b20d981e344fac0b3509879456f
      deploys:
        app:
          sha: cd58c87978165b20d981e344fac0b3509879456f
          deployed_at: "2026-06-30T08:16:42Z"
          deployed_by: joshua-temple
  latest_release:
    version: v0.1.0
    sha: cd58c87978165b20d981e344fac0b3509879456f
    released_on: "2026-06-30T08:18:58Z"
    released_by: joshua-temple
